### ISSUE TITLE
0.16.18 wants braking force positive.

### ISSUE THREAD

**Issue by georgehank** [DedlySpyder/Avatars#10]
Guess it doesn't like avatar-control-center's "braking_power = "0W""… haven't tried changing it though.

**Comment by DedlySpyder** [comment]
Sigh, yep that looks like that's the issue. Publishing a fix now to the mod portal.

Thanks for the report!

**Comment by DedlySpyder** [comment]
Version 0.4.10 of Avatars made to fix this (mod portal didn't like 0.4.9)
